return {
    Name = "StudioSignal",
    Version = "v1.1",
    Copyright = "© 2026 VOIDKSA",
    ApplicationId = "",
    Scope = "sdk.social_layer_presence",
    ApiBase = "https://discord.com/api/v10",
    ContourUrl = "https://create.roblox.com/store/asset/94088881259293",
    SupportUrl = "https://discord.gg/sWszV6FQbW",
    DeveloperUrl = "https://discord.com/developers/applications",
    MinUpdateSeconds = 15,
    HeartbeatSeconds = 120,
}
